import Head from 'next/head'
import Link from 'next/link'
import Cookies from 'js-cookie';
import 'react-toastify/dist/ReactToastify.css';
import { Menu } from '@headlessui/react';
import { ToastContainer } from 'react-toastify';
import { useContext, useEffect, useState } from 'react';


import DropdownLink from './DropdownLink';
import { Store } from '@/context/Store';
import { signOut, useSession } from 'next-auth/react';

const Layout = ({ children, title }) => {

    const { status, data: session } = useSession();
    const { state, dispatch } = useContext(Store);
    const { cart } = state;
    const [cartItemsCount, setCartItemsCount] = useState(0);

    useEffect(() => {
        setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.qty, 0))
    }, [cart.cartItems]);

    const logoutHandler = () => {
        Cookies.remove('cart');
        dispatch({ type: 'CART_RESET' });
        signOut({ callbackUrl: '/Login' });
        // location.reload();
    }

    return (
        <>
            <Head>
                <title>{title ? title + ' - Robotz' : 'Robotz'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ToastContainer position='bottom-center' limit={1} />

            <div className='flex min-h-screen flex-col justify-between'>
                <header>
                    <nav className='flex h-12 justify-between shadow-md items-center px-4'>
                        <Link href="/" className="text-lg font-bold">
                            RobotZ
                        </Link>
                        <div>
                            <Link className="p-2" href="/Cart">
                                Cart:
                                {cartItemsCount > 0 && (
                                    <span className='ml-1 rounded-full bg-pink-500 px-2
                                     py-1 text-xs font-bold text-white'>
                                        {cartItemsCount}
                                    </span>
                                )}
                            </Link>
                            {status === 'loading'
                                ? ('LOADING...')
                                : session?.user
                                    ? (<Menu as="div" className="relative inline-block">
                                        <Menu.Button className='text-amber-700'>
                                            {session.user.name}
                                        </Menu.Button>
                                        <Menu.Items className='bg-white absolute right-0 w-56 origin-top-right shadow-lg'>
                                            <Menu.Item>
                                                <DropdownLink className='dropdown-link' href='/profile'>
                                                    Profile
                                                </DropdownLink>
                                            </Menu.Item>
                                            <Menu.Item>
                                                <DropdownLink className='dropdown-link' href='/order-history'>
                                                    Orders History
                                                </DropdownLink>
                                            </Menu.Item>
                                            <Menu.Item>
                                                <a className='dropdown-link' href='#'
                                                    onClick={logoutHandler}>
                                                    Logout
                                                </a>
                                            </Menu.Item>
                                        </Menu.Items>
                                    </Menu>)
                                    : (
                                        <Link href="/Login" className="p-2">Login</Link>
                                    )
                            }
                        </div>
                    </nav>
                </header>
                <main className='container m-auto mt-4 px-4'>{children}</main>
                <footer className='flex justify-center items-center h-10 shadow-inner'>
                    footer
                </footer>
            </div>
        </>
    )
}

export default Layout